root: .

extends: :nothing

require: []

include_categories: []

exclude_categories: []

ignore:
  - node_modules/*

ConvertIncludeToRender:
  enabled: true
  ignore: []

IncludeInRender:
  enabled: true
  ignore: []

LiquidTag:
  enabled: true
  ignore: []
  min_consecutive_statements: 5

MissingTemplate:
  enabled: true
  ignore: []
  ignore_missing: []

RequiredLayoutObject:
  enabled: true
  ignore: []

SpaceInsideBraces:
  enabled: true
  ignore: []

InvalidArgs:
  enabled: true
  ignore: []

SyntaxError:
  enabled: true
  ignore: []

TemplateLength:
  enabled: true
  ignore: []
  max_length: 600

UnknownFilter:
  enabled: true
  ignore: []

UnreachableCode:
  enabled: true
  ignore: []

UnusedAssign:
  enabled: true
  ignore: []

UnusedPartial:
  enabled: true
  ignore: []

ValidYaml:
  enabled: true
  ignore: []

UndefinedObject:
  enabled: true
  ignore: []

DeprecatedFilter:
  enabled: true
  ignore: []

MissingEnableComment:
  enabled: true
  ignore: []

ParserBlockingJavaScript:
  enabled: true
  ignore: []

ImgWidthAndHeight:
  enabled: true
  ignore: []

ImgLazyLoading:
  enabled: true
  ignore: []

FormAction:
  enabled: true
  ignore: []

FormAuthenticityToken:
  enabled: true
  ignore: []

GraphqlInForLoop:
  enabled: true
  ignore: []

HtmlParsingError:
  enabled: true
  ignore: []

ParseJsonFormat:
  enabled: false
  start_level: 0
  indent: '  '
