root: .

extends: :nothing

require: []

include_categories: []

exclude_categories: []

ignore:
  - node_modules/*

ConvertIncludeToRender:
  enabled: true
  ignore: []

LiquidTag:
  enabled: true
  ignore: []
  min_consecutive_statements: 4

MissingTemplate:
  enabled: true
  ignore: []
  ignore_missing: []

RequiredLayoutObject:
  enabled: true
  ignore: []

SpaceInsideBraces:
  enabled: true
  ignore: []

SyntaxError:
  enabled: true
  ignore: []

TemplateLength:
  enabled: true
  ignore: []
  max_length: 200
  # Exclude content of {% schema %} in line count
  exclude_schema: true

UnknownFilter:
  enabled: true
  ignore: []

UnusedAssign:
  enabled: true
  ignore: []

UnusedPartial:
  enabled: true
  ignore: []

ValidYaml:
  enabled: true
  ignore: []

UndefinedObject:
  enabled: true
  ignore: []
  exclude_partials: true
  config_type: :theme_app_extension

RequiredDirectories:
  enabled: false
  ignore: []

DeprecatedFilter:
  enabled: true
  ignore: []

MissingEnableComment:
  enabled: true
  ignore: []

ParserBlockingJavaScript:
  enabled: true
  ignore: []

ParserBlockingScriptTag:
  enabled: true

AssetSizeJavaScript:
  enabled: true
  severity: suggestion
  ignore: []
  threshold_in_bytes: 10_000

AssetSizeCSS:
  enabled: true
  severity: suggestion
  ignore: []
  threshold_in_bytes: 100_000

ImgWidthAndHeight:
  enabled: true
  ignore: []

RemoteAsset:
  enabled: true
  ignore: []

AssetUrlFilters:
  enabled: true
  ignore: []

ImgLazyLoading:
  enabled: true
  ignore: []

HtmlParsingError:
  enabled: true
  ignore: []

AssetSizeAppBlockJavaScript:
  enabled: true
  severity: suggestion
  ignore: []
  threshold_in_bytes: 10_000

AssetSizeAppBlockCSS:
  enabled: true
  severity: suggestion
  ignore: []
  threshold_in_bytes: 100_000

PaginationSize:
  enabled: true
  ignore: []
  min_size: 1
  max_size: 50
